-- 建表
-- 用户表
CREATE TABLE IF NOT EXISTS CUX_USERS
(
  USER_ID          INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COLLATE utf8_general_ci COMMENT '用户ID 主键',
  USER_NAME        VARCHAR(250)                       NOT NULL COLLATE utf8_general_ci COMMENT '用户名称',
  PASSWORD         VARCHAR(30)                        NOT NULL COLLATE utf8_general_ci COMMENT '用户密码',
  SEX              ENUM('F','M') NOT NULL COLLATE utf8_general_ci COMMENT '性别M-Male/F-Female',
  AGE              INT COLLATE utf8_general_ci COMMENT '年龄 范围1-200',
  PHONE_NUMBER     VARCHAR(30) COLLATE utf8_general_ci COMMENT '电话',
  CREATION_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COLLATE utf8_general_ci COMMENT '创建时间',
  LAST_UPDATE_DATE DATETIME NOT NULL COLLATE utf8_general_ci COMMENT '更新时间',
  COMMENTS         VARCHAR(2000) COLLATE utf8_general_ci COMMENT '备注',
    CHECK (AGE BETWEEN 1 AND 200)
) AUTO_INCREMENT=1000 COLLATE utf8_general_ci COMMENT '用户信息表';


-- 待办事项表
CREATE TABLE IF NOT EXISTS CUX_TODO_ITEMS
(
  TODO_ITEM_ID      INT PRIMARY KEY              AUTO_INCREMENT NOT NULL  COMMENT '待办事项ID',
  USER_ID           INT UNSIGNED                                NOT NULL  COMMENT '所属用户ID',
  TODO_ITEM_TITLE   VARCHAR(250)                                NOT NULL  COMMENT '待办事项标题',
  TODO_ITEM_CONTENT VARCHAR(2000)                               NULL      COMMENT '待办事项内容',
  PRIORITY          ENUM('LOW','HIGH','MEDIUM') DEFAULT 'LOW'   NOT NULL  COMMENT '优先级 LOW/HIGH/MEDIUM',
  CREATION_DATE     DATETIME         DEFAULT CURRENT_TIMESTAMP  NOT NULL  COMMENT '创建时间',
  LAST_UPDATE_DATE  DATETIME         DEFAULT CURRENT_TIMESTAMP  NOT NULL  COMMENT '更新时间',
  COMMENTS          VARCHAR(2000)                               NULL      COMMENT '备注',
  CONSTRAINT ITEMS_USERS_USER_ID_FK
    FOREIGN KEY(USER_ID) REFERENCES CUX_USERS(USER_ID)
      ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE utf8_general_ci AUTO_INCREMENT=1000 COMMENT '待办事项表';

-- 导入数据
INSERT INTO CUX_TODO_ITEMS VALUES(NULL ,1000,'开会','出项目方案','HIGH',CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP ,'很重要');
INSERT INTO CUX_TODO_ITEMS VALUES(NULL ,1000,'健身','塑造完美体型','LOW',CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP ,'');
